### ISSUE TITLE
S3 enhancements and bug fixes

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-aws#239]
### Issue description

These include supporting additional content type for S3 object, adding a dedicated MinIO plugin and more

```[tasklist]
### Tasks
- [ ] https://github.com/kestra-io/plugin-aws/issues/214
- [ ] https://github.com/kestra-io/plugin-aws/issues/216
- [ ] https://github.com/kestra-io/plugin-aws/issues/144
```

**Comment by anna-geller** [comment]
only MinIO left
